services:
 catalogdb:
  image: postgres

volumes:
 postgress_catalog:

  # catalogapi:
  #   image: ${DOCKER_REGISTRY-}catalogapi
  #   build:
  #     context: .
  #     dockerfile: Services/Catalog/CatalogAPI/Dockerfile
 
